//! # typewriter-plugin-ruby
//!
//! Ruby (Sorbet) emitter plugin for typewriter.
//!
//! Generates Sorbet-compatible `.rbi` type signature files from Rust structs and enums.
//!
//! ## Type Mappings
//!
//! | Rust Type | Ruby/Sorbet Type |
//! |-----------|------------------|
//! | `String` | `String` |
//! | `bool` | `T::Boolean` |
//! | `u8`–`u128`, `i8`–`i128` | `Integer` |
//! | `f32`, `f64` | `Float` |
//! | `Option<T>` | `T.nilable(T)` |
//! | `Vec<T>` | `T::Array[T]` |
//! | `HashMap<K, V>` | `T::Hash[K, V]` |
//! | `Uuid` | `String` |
//! | `DateTime` | `Time` |

use typewriter_plugin::prelude::*;

/// Ruby/Sorbet language mapper.
pub struct RubyMapper {
    file_style: FileStyle,
}

impl RubyMapper {
    pub fn new() -> Self {
        Self {
            file_style: FileStyle::SnakeCase,
        }
    }

    pub fn with_file_style(mut self, style: FileStyle) -> Self {
        self.file_style = style;
        self
    }
}

impl Default for RubyMapper {
    fn default() -> Self {
        Self::new()
    }
}

impl TypeMapper for RubyMapper {
    fn map_primitive(&self, ty: &PrimitiveType) -> String {
        match ty {
            PrimitiveType::String => "String".to_string(),
            PrimitiveType::Bool => "T::Boolean".to_string(),
            PrimitiveType::U8 | PrimitiveType::U16 | PrimitiveType::U32
            | PrimitiveType::U64 | PrimitiveType::U128
            | PrimitiveType::I8 | PrimitiveType::I16 | PrimitiveType::I32
            | PrimitiveType::I64 | PrimitiveType::I128 => "Integer".to_string(),
            PrimitiveType::F32 | PrimitiveType::F64 => "Float".to_string(),
            PrimitiveType::Uuid => "String".to_string(),
            PrimitiveType::DateTime => "Time".to_string(),
            PrimitiveType::NaiveDate => "Date".to_string(),
            PrimitiveType::JsonValue => "T.untyped".to_string(),
        }
    }

    fn map_option(&self, inner: &TypeKind) -> String {
        format!("T.nilable({})", self.map_type(inner))
    }

    fn map_vec(&self, inner: &TypeKind) -> String {
        format!("T::Array[{}]", self.map_type(inner))
    }

    fn map_hashmap(&self, key: &TypeKind, value: &TypeKind) -> String {
        format!("T::Hash[{}, {}]", self.map_type(key), self.map_type(value))
    }

    fn map_tuple(&self, elements: &[TypeKind]) -> String {
        let inner: Vec<String> = elements.iter().map(|e| self.map_type(e)).collect();
        format!("[{}]", inner.join(", "))
    }

    fn map_named(&self, name: &str) -> String {
        name.to_string()
    }

    fn map_generic(&self, name: &str, params: &[TypeKind]) -> String {
        let param_strs: Vec<String> = params.iter().map(|p| self.map_type(p)).collect();
        format!("{}[{}]", name, param_strs.join(", "))
    }

    fn emit_struct(&self, def: &StructDef) -> String {
        let mut output = String::new();

        // Doc comment
        if let Some(doc) = &def.doc {
            output.push_str(&format!("# {}\n", doc.trim()));
        }

        // Class declaration
        if def.generics.is_empty() {
            output.push_str(&format!("class {} < T::Struct\n", def.name));
        } else {
            output.push_str(&format!(
                "class {} < T::Struct\n  extend T::Generic\n\n",
                def.name
            ));
            for g in &def.generics {
                output.push_str(&format!("  {} = type_member\n", g));
            }
            output.push('\n');
        }

        for field in &def.fields {
            if field.skip {
                continue;
            }

            // Field doc comment
            if let Some(doc) = &field.doc {
                output.push_str(&format!("  # {}\n", doc.trim()));
            }

            let field_name = field.rename.as_deref().unwrap_or(&field.name);
            let type_str = field
                .type_override
                .clone()
                .unwrap_or_else(|| self.map_type(&field.ty));

            if field.optional {
                output.push_str(&format!(
                    "  const :{}, {}, default: nil\n",
                    field_name, type_str
                ));
            } else {
                output.push_str(&format!("  const :{}, {}\n", field_name, type_str));
            }
        }

        output.push_str("end\n");
        output
    }

    fn emit_enum(&self, def: &EnumDef) -> String {
        let all_unit = def.variants.iter().all(|v| matches!(v.kind, VariantKind::Unit));

        if all_unit {
            self.emit_string_enum(def)
        } else {
            self.emit_sealed_enum(def)
        }
    }

    fn file_header(&self, type_name: &str) -> String {
        format!(
            "# typed: strict\n\
             # Auto-generated by typewriter v0.5.2. DO NOT EDIT.\n\
             # Source: {}\n\
             # Regenerate: cargo typewriter generate\n\n",
            type_name
        )
    }

    fn file_extension(&self) -> &str {
        "rbi"
    }

    fn file_naming(&self, type_name: &str) -> String {
        to_file_style(type_name, self.file_style)
    }

    fn emit_imports(&self, _def: &TypeDef) -> String {
        String::new()
    }
}

impl RubyMapper {
    fn emit_string_enum(&self, def: &EnumDef) -> String {
        let mut output = String::new();

        if let Some(doc) = &def.doc {
            output.push_str(&format!("# {}\n", doc.trim()));
        }

        output.push_str(&format!("class {} < T::Enum\n  enums do\n", def.name));

        for variant in &def.variants {
            let name = variant.rename.as_deref().unwrap_or(&variant.name);
            if let Some(doc) = &variant.doc {
                output.push_str(&format!("    # {}\n", doc.trim()));
            }
            output.push_str(&format!(
                "    {} = new('{}')\n",
                name, name
            ));
        }

        output.push_str("  end\nend\n");
        output
    }

    fn emit_sealed_enum(&self, def: &EnumDef) -> String {
        let mut output = String::new();

        if let Some(doc) = &def.doc {
            output.push_str(&format!("# {}\n", doc.trim()));
        }

        output.push_str(&format!(
            "module {}\n  extend T::Helpers\n  sealed!\n\n",
            def.name
        ));

        for variant in &def.variants {
            let variant_name = variant.rename.as_deref().unwrap_or(&variant.name);

            match &variant.kind {
                VariantKind::Unit => {
                    output.push_str(&format!(
                        "  class {} < T::Struct\n    include {}\n  end\n\n",
                        variant_name, def.name
                    ));
                }
                VariantKind::Struct(fields) => {
                    output.push_str(&format!(
                        "  class {} < T::Struct\n    include {}\n\n",
                        variant_name, def.name
                    ));
                    for field in fields {
                        if field.skip { continue; }
                        let fname = field.rename.as_deref().unwrap_or(&field.name);
                        let ftype = field
                            .type_override
                            .clone()
                            .unwrap_or_else(|| self.map_type(&field.ty));
                        output.push_str(&format!("    const :{}, {}\n", fname, ftype));
                    }
                    output.push_str("  end\n\n");
                }
                VariantKind::Tuple(types) => {
                    output.push_str(&format!(
                        "  class {} < T::Struct\n    include {}\n\n",
                        variant_name, def.name
                    ));
                    for (i, ty) in types.iter().enumerate() {
                        output.push_str(&format!(
                            "    const :field_{}, {}\n",
                            i, self.map_type(ty)
                        ));
                    }
                    output.push_str("  end\n\n");
                }
            }
        }

        output.push_str("end\n");
        output
    }
}

/// Ruby emitter plugin entry point.
pub struct RubyPlugin;

impl RubyPlugin {
    pub fn new() -> Self {
        Self
    }
}

impl Default for RubyPlugin {
    fn default() -> Self {
        Self::new()
    }
}

impl EmitterPlugin for RubyPlugin {
    fn language_id(&self) -> &str {
        "ruby"
    }

    fn language_name(&self) -> &str {
        "Ruby (Sorbet)"
    }

    fn version(&self) -> &str {
        "0.1.0"
    }

    fn default_output_dir(&self) -> &str {
        "./generated/ruby"
    }

    fn file_extension(&self) -> &str {
        "rbi"
    }

    fn mapper(&self, config: &PluginConfig) -> Box<dyn TypeMapper> {
        let mut mapper = RubyMapper::new();
        if let Some(style_str) = config.file_style.as_deref() {
            if let Some(style) = FileStyle::from_str(style_str) {
                mapper = mapper.with_file_style(style);
            }
        }
        Box::new(mapper)
    }
}

typewriter_plugin::declare_plugin!(RubyPlugin);

#[cfg(test)]
mod tests {
    use super::*;

    fn mapper() -> RubyMapper {
        RubyMapper::new()
    }

    #[test]
    fn test_primitive_mappings() {
        let m = mapper();
        assert_eq!(m.map_primitive(&PrimitiveType::String), "String");
        assert_eq!(m.map_primitive(&PrimitiveType::Bool), "T::Boolean");
        assert_eq!(m.map_primitive(&PrimitiveType::U32), "Integer");
        assert_eq!(m.map_primitive(&PrimitiveType::I64), "Integer");
        assert_eq!(m.map_primitive(&PrimitiveType::F64), "Float");
        assert_eq!(m.map_primitive(&PrimitiveType::Uuid), "String");
        assert_eq!(m.map_primitive(&PrimitiveType::DateTime), "Time");
        assert_eq!(m.map_primitive(&PrimitiveType::JsonValue), "T.untyped");
    }

    #[test]
    fn test_option_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_option(&TypeKind::Primitive(PrimitiveType::U32)),
            "T.nilable(Integer)"
        );
    }

    #[test]
    fn test_vec_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_vec(&TypeKind::Primitive(PrimitiveType::String)),
            "T::Array[String]"
        );
    }

    #[test]
    fn test_hashmap_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_hashmap(
                &TypeKind::Primitive(PrimitiveType::String),
                &TypeKind::Primitive(PrimitiveType::U32)
            ),
            "T::Hash[String, Integer]"
        );
    }

    #[test]
    fn test_emit_simple_struct() {
        let m = mapper();
        let def = StructDef {
            name: "User".to_string(),
            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    ty: TypeKind::Primitive(PrimitiveType::Uuid),
                    optional: false, rename: None, doc: None,
                    skip: false, flatten: false, type_override: None,
                },
                FieldDef {
                    name: "age".to_string(),
                    ty: TypeKind::Option(Box::new(TypeKind::Primitive(PrimitiveType::U32))),
                    optional: true, rename: None, doc: None,
                    skip: false, flatten: false, type_override: None,
                },
            ],
            doc: None,
            generics: vec![],
        };

        let output = m.emit_struct(&def);
        assert!(output.contains("class User < T::Struct"));
        assert!(output.contains("const :id, String"));
        assert!(output.contains("const :age, T.nilable(Integer), default: nil"));
    }

    #[test]
    fn test_emit_simple_enum() {
        let m = mapper();
        let def = EnumDef {
            name: "Role".to_string(),
            variants: vec![
                VariantDef { name: "Admin".to_string(), rename: None, kind: VariantKind::Unit, doc: None },
                VariantDef { name: "User".to_string(), rename: None, kind: VariantKind::Unit, doc: None },
            ],
            representation: EnumRepr::External,
            doc: None,
        };

        let output = m.emit_enum(&def);
        assert!(output.contains("class Role < T::Enum"));
        assert!(output.contains("Admin = new('Admin')"));
        assert!(output.contains("User = new('User')"));
    }

    #[test]
    fn test_plugin_metadata() {
        let plugin = RubyPlugin::new();
        assert_eq!(plugin.language_id(), "ruby");
        assert_eq!(plugin.language_name(), "Ruby (Sorbet)");
        assert_eq!(plugin.file_extension(), "rbi");
        assert_eq!(plugin.api_version(), PLUGIN_API_VERSION);
    }
}
