use assert_cmd::Command;
use serde_json::Value;
use std::fs;
use std::path::Path;
use tempfile::TempDir;

fn setup_project() -> TempDir {
    let temp = tempfile::tempdir().unwrap();
    fs::create_dir_all(temp.path().join("src/models")).unwrap();

    fs::write(
        temp.path().join("Cargo.toml"),
        r#"
[package]
name = "demo"
version = "0.1.0"
edition = "2021"
"#,
    )
    .unwrap();

    fs::write(
        temp.path().join("src/models/user.rs"),
        r#"
#[derive(TypeWriter)]
#[sync_to(typescript, python)]
pub struct User {
    pub id: String,
    pub email: String,
}
"#,
    )
    .unwrap();

    temp
}

fn run_typewriter(project: &Path, args: &[&str]) -> assert_cmd::assert::Assert {
    let mut cmd = Command::cargo_bin("typewriter").unwrap();
    cmd.current_dir(project).args(args).assert()
}

fn run_cargo_typewriter(project: &Path, args: &[&str]) -> assert_cmd::assert::Assert {
    let mut cmd = Command::cargo_bin("cargo-typewriter").unwrap();
    cmd.current_dir(project).args(args).assert()
}

#[test]
fn generate_all_writes_expected_files() {
    let temp = setup_project();

    run_typewriter(temp.path(), &["generate", "--all"]).success();

    assert!(temp.path().join("generated/typescript/user.ts").exists());
    assert!(temp.path().join("generated/python/user.py").exists());
}

#[test]
fn generate_single_file_lang_filter() {
    let temp = setup_project();

    run_typewriter(
        temp.path(),
        &["generate", "src/models/user.rs", "--lang", "typescript"],
    )
    .success();

    assert!(temp.path().join("generated/typescript/user.ts").exists());
    assert!(!temp.path().join("generated/python/user.py").exists());
}

#[test]
fn generate_diff_prints_unified_diff() {
    let temp = setup_project();

    run_typewriter(temp.path(), &["generate", "--all"]).success();

    let ts_path = temp.path().join("generated/typescript/user.ts");
    fs::write(&ts_path, "// changed\n").unwrap();

    run_typewriter(temp.path(), &["generate", "--all", "--diff"])
        .success()
        .stdout(predicates::str::contains(
            "--- a/generated/typescript/user.ts",
        ));
}

#[test]
fn check_detects_drift_and_ci_fails() {
    let temp = setup_project();
    run_typewriter(temp.path(), &["generate", "--all"]).success();

    let ts_path = temp.path().join("generated/typescript/user.ts");
    fs::write(&ts_path, "// changed\n").unwrap();

    let py_path = temp.path().join("generated/python/user.py");
    fs::remove_file(&py_path).unwrap();

    let orphan_path = temp.path().join("generated/typescript/orphan.ts");
    fs::create_dir_all(orphan_path.parent().unwrap()).unwrap();
    fs::write(
        &orphan_path,
        "// Auto-generated by typewriter v0.3.0. DO NOT EDIT.\n",
    )
    .unwrap();

    let output = Command::cargo_bin("typewriter")
        .unwrap()
        .current_dir(temp.path())
        .args(["check", "--json"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();

    let report: Value = serde_json::from_slice(&output).unwrap();
    let summary = &report["summary"];
    assert!(summary["out_of_sync"].as_u64().unwrap() >= 1);
    assert!(summary["missing"].as_u64().unwrap() >= 1);
    assert!(summary["orphaned"].as_u64().unwrap() >= 1);

    run_typewriter(temp.path(), &["check", "--ci"]).failure();
}

#[test]
fn check_json_out_writes_report_file() {
    let temp = setup_project();
    run_typewriter(temp.path(), &["generate", "--all"]).success();

    run_typewriter(
        temp.path(),
        &["check", "--json", "--json-out", "reports/drift.json"],
    )
    .success();

    let report_path = temp.path().join("reports/drift.json");
    assert!(report_path.exists());

    let parsed: Value = serde_json::from_slice(&fs::read(report_path).unwrap()).unwrap();
    assert!(parsed["entries"].is_array());
}

#[test]
fn cargo_typewriter_matches_generate_command() {
    let temp = setup_project();

    run_cargo_typewriter(temp.path(), &["generate", "--all"]).success();

    assert!(temp.path().join("generated/typescript/user.ts").exists());
    assert!(temp.path().join("generated/python/user.py").exists());
}
