//! Kotlin type mapper implementation.

use typewriter_core::ir::*;
use typewriter_core::mapper::TypeMapper;
use typewriter_core::naming::{FileStyle, to_file_style};

use crate::emitter;

/// Kotlin language mapper.
///
/// Generates Kotlin `@Serializable` data classes and sealed classes from Rust types.
pub struct KotlinMapper {
    /// File naming style (default: `PascalCase`)
    pub file_style: FileStyle,
    /// Package name (default: "types")
    pub package_name: String,
}

impl KotlinMapper {
    pub fn new() -> Self {
        Self {
            file_style: FileStyle::PascalCase,
            package_name: "types".to_string(),
        }
    }

    pub fn with_file_style(mut self, style: FileStyle) -> Self {
        self.file_style = style;
        self
    }

    pub fn with_package_name(mut self, name: &str) -> Self {
        self.package_name = name.to_string();
        self
    }
}

impl Default for KotlinMapper {
    fn default() -> Self {
        Self::new()
    }
}

impl TypeMapper for KotlinMapper {
    fn map_primitive(&self, ty: &PrimitiveType) -> String {
        match ty {
            PrimitiveType::String => "String".to_string(),
            PrimitiveType::Bool => "Boolean".to_string(),
            PrimitiveType::U8 => "UByte".to_string(),
            PrimitiveType::U16 => "UShort".to_string(),
            PrimitiveType::U32 => "UInt".to_string(),
            PrimitiveType::U64 => "ULong".to_string(),
            // Kotlin has no UInt128; use String for JSON safety
            PrimitiveType::U128 => "String".to_string(),
            PrimitiveType::I8 => "Byte".to_string(),
            PrimitiveType::I16 => "Short".to_string(),
            PrimitiveType::I32 => "Int".to_string(),
            PrimitiveType::I64 => "Long".to_string(),
            // Same as U128
            PrimitiveType::I128 => "String".to_string(),
            PrimitiveType::F32 => "Float".to_string(),
            PrimitiveType::F64 => "Double".to_string(),
            PrimitiveType::Uuid => "String".to_string(),
            PrimitiveType::DateTime => "String".to_string(),
            PrimitiveType::NaiveDate => "String".to_string(),
            PrimitiveType::JsonValue => "kotlinx.serialization.json.JsonElement".to_string(),
        }
    }

    fn map_option(&self, inner: &TypeKind) -> String {
        format!("{}?", self.map_type(inner))
    }

    fn map_vec(&self, inner: &TypeKind) -> String {
        format!("List<{}>", self.map_type(inner))
    }

    fn map_hashmap(&self, key: &TypeKind, value: &TypeKind) -> String {
        format!("Map<{}, {}>", self.map_type(key), self.map_type(value))
    }

    fn map_tuple(&self, elements: &[TypeKind]) -> String {
        if elements.len() == 2 {
            format!(
                "Pair<{}, {}>",
                self.map_type(&elements[0]),
                self.map_type(&elements[1])
            )
        } else if elements.len() == 3 {
            format!(
                "Triple<{}, {}, {}>",
                self.map_type(&elements[0]),
                self.map_type(&elements[1]),
                self.map_type(&elements[2])
            )
        } else {
            // For 4+ elements, generate a list (Kotlin has no built-in tuple >3)
            let type_strs: Vec<String> = elements.iter().map(|e| self.map_type(e)).collect();
            format!("List<Any> /* ({}) */", type_strs.join(", "))
        }
    }

    fn map_named(&self, name: &str) -> String {
        name.to_string()
    }

    fn emit_struct(&self, def: &StructDef) -> String {
        emitter::render_struct(self, def)
    }

    fn emit_enum(&self, def: &EnumDef) -> String {
        emitter::render_enum(self, def)
    }

    fn file_header(&self, type_name: &str) -> String {
        format!(
            "// Code generated by typewriter v0.4.1. DO NOT EDIT.\n\
             // Source: {}\n\n\
             package {}\n\n\
             import kotlinx.serialization.Serializable\n\
             import kotlinx.serialization.SerialName\n\n",
            type_name, self.package_name
        )
    }

    fn file_extension(&self) -> &str {
        "kt"
    }

    fn emit_imports(&self, _def: &TypeDef) -> String {
        // Core imports are handled in file_header.
        // No additional per-type imports needed.
        String::new()
    }

    fn file_naming(&self, type_name: &str) -> String {
        to_file_style(type_name, self.file_style)
    }

    fn map_generic(&self, name: &str, params: &[TypeKind]) -> String {
        let param_strs: Vec<String> = params.iter().map(|p| self.map_type(p)).collect();
        format!("{}<{}>", name, param_strs.join(", "))
    }
}
