//! GraphQL SDL type mapper implementation.

use typewriter_core::ir::*;
use typewriter_core::mapper::TypeMapper;
use typewriter_core::naming::{to_file_style, FileStyle};

use crate::emitter;

/// GraphQL SDL language mapper.
///
/// Generates GraphQL Schema Definition Language types from Rust structs and enums.
///
/// ## Type Mappings
///
/// | Rust | GraphQL |
/// |------|---------|
/// | `struct` | `type TypeName { ... }` |
/// | Simple enum | `enum TypeName { ... }` |
/// | Data-carrying enum | `union TypeName = ...` + variant types |
/// | `String` | `String` |
/// | `bool` | `Boolean` |
/// | `u8`–`u32`, `i8`–`i32` | `Int` |
/// | `f32`, `f64` | `Float` |
/// | `u64`, `i64` etc. | `String` (BigInt not in GraphQL spec) |
/// | `Option<T>` | nullable (no `!`) |
/// | `Vec<T>` | `[T!]` |
/// | `HashMap<K,V>` | `JSON` (custom scalar) |
/// | `Uuid` | `ID` |
/// | `DateTime` | `DateTime` (custom scalar) |
/// | `JsonValue` | `JSON` (custom scalar) |
pub struct GraphQLMapper {
    /// File naming style (default: `snake_case`)
    pub file_style: FileStyle,
}

impl GraphQLMapper {
    pub fn new() -> Self {
        Self {
            file_style: FileStyle::SnakeCase,
        }
    }

    pub fn with_file_style(mut self, style: FileStyle) -> Self {
        self.file_style = style;
        self
    }
}

impl Default for GraphQLMapper {
    fn default() -> Self {
        Self::new()
    }
}

impl TypeMapper for GraphQLMapper {
    fn map_primitive(&self, ty: &PrimitiveType) -> String {
        match ty {
            PrimitiveType::String => "String".to_string(),
            PrimitiveType::Bool => "Boolean".to_string(),
            PrimitiveType::U8 | PrimitiveType::U16 | PrimitiveType::U32 => "Int".to_string(),
            PrimitiveType::I8 | PrimitiveType::I16 | PrimitiveType::I32 => "Int".to_string(),
            PrimitiveType::F32 | PrimitiveType::F64 => "Float".to_string(),
            // GraphQL has no bigint in the spec; use String for safe JSON transport
            PrimitiveType::U64 | PrimitiveType::U128 => "String".to_string(),
            PrimitiveType::I64 | PrimitiveType::I128 => "String".to_string(),
            PrimitiveType::Uuid => "ID".to_string(),
            PrimitiveType::DateTime | PrimitiveType::NaiveDate => "DateTime".to_string(),
            PrimitiveType::JsonValue => "JSON".to_string(),
        }
    }

    fn map_option(&self, inner: &TypeKind) -> String {
        // In GraphQL, optional means the field is nullable (no `!` suffix).
        // We return the inner type without the `!` marker.
        self.map_type(inner)
    }

    fn map_vec(&self, inner: &TypeKind) -> String {
        format!("[{}!]", self.map_type(inner))
    }

    fn map_hashmap(&self, _key: &TypeKind, _value: &TypeKind) -> String {
        // GraphQL has no map type; use a JSON custom scalar
        "JSON".to_string()
    }

    fn map_tuple(&self, _elements: &[TypeKind]) -> String {
        // GraphQL has no tuple type; fall back to JSON
        "JSON".to_string()
    }

    fn map_named(&self, name: &str) -> String {
        name.to_string()
    }

    fn emit_struct(&self, def: &StructDef) -> String {
        emitter::render_type(self, def)
    }

    fn emit_enum(&self, def: &EnumDef) -> String {
        emitter::render_enum(self, def)
    }

    fn file_header(&self, type_name: &str) -> String {
        format!(
            "# Auto-generated by typewriter v0.4.0. DO NOT EDIT.\n\
             # Source: {}\n\n",
            type_name
        )
    }

    fn file_extension(&self) -> &str {
        "graphql"
    }

    fn emit_imports(&self, def: &TypeDef) -> String {
        // Collect custom scalars that need to be declared
        let mut needs_datetime = false;
        let mut needs_json = false;

        fn scan_type(ty: &TypeKind, needs_datetime: &mut bool, needs_json: &mut bool) {
            match ty {
                TypeKind::Primitive(p) => match p {
                    PrimitiveType::DateTime | PrimitiveType::NaiveDate => {
                        *needs_datetime = true;
                    }
                    PrimitiveType::JsonValue => {
                        *needs_json = true;
                    }
                    _ => {}
                },
                TypeKind::Option(inner) | TypeKind::Vec(inner) => {
                    scan_type(inner, needs_datetime, needs_json);
                }
                TypeKind::HashMap(_, _) => {
                    *needs_json = true;
                }
                TypeKind::Tuple(_) => {
                    *needs_json = true;
                }
                TypeKind::Generic(_, params) => {
                    for p in params {
                        scan_type(p, needs_datetime, needs_json);
                    }
                }
                _ => {}
            }
        }

        match def {
            TypeDef::Struct(s) => {
                for field in &s.fields {
                    if !field.skip {
                        scan_type(&field.ty, &mut needs_datetime, &mut needs_json);
                    }
                }
            }
            TypeDef::Enum(e) => {
                for variant in &e.variants {
                    match &variant.kind {
                        VariantKind::Struct(fields) => {
                            for field in fields {
                                if !field.skip {
                                    scan_type(&field.ty, &mut needs_datetime, &mut needs_json);
                                }
                            }
                        }
                        VariantKind::Tuple(types) => {
                            for ty in types {
                                scan_type(ty, &mut needs_datetime, &mut needs_json);
                            }
                        }
                        VariantKind::Unit => {}
                    }
                }
            }
        }

        let mut output = String::new();
        if needs_datetime {
            output.push_str("scalar DateTime\n");
        }
        if needs_json {
            output.push_str("scalar JSON\n");
        }
        if !output.is_empty() {
            output.push('\n');
        }
        output
    }

    fn file_naming(&self, type_name: &str) -> String {
        to_file_style(type_name, self.file_style)
    }

    fn map_generic(&self, name: &str, _params: &[TypeKind]) -> String {
        // GraphQL doesn't have generics — just reference the base type name
        name.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mapper() -> GraphQLMapper {
        GraphQLMapper::new()
    }

    #[test]
    fn test_primitive_mappings() {
        let m = mapper();
        assert_eq!(m.map_primitive(&PrimitiveType::String), "String");
        assert_eq!(m.map_primitive(&PrimitiveType::Bool), "Boolean");
        assert_eq!(m.map_primitive(&PrimitiveType::U32), "Int");
        assert_eq!(m.map_primitive(&PrimitiveType::I32), "Int");
        assert_eq!(m.map_primitive(&PrimitiveType::F64), "Float");
        assert_eq!(m.map_primitive(&PrimitiveType::U64), "String");
        assert_eq!(m.map_primitive(&PrimitiveType::I64), "String");
        assert_eq!(m.map_primitive(&PrimitiveType::Uuid), "ID");
        assert_eq!(m.map_primitive(&PrimitiveType::DateTime), "DateTime");
        assert_eq!(m.map_primitive(&PrimitiveType::JsonValue), "JSON");
    }

    #[test]
    fn test_option_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_option(&TypeKind::Primitive(PrimitiveType::U32)),
            "Int"
        );
    }

    #[test]
    fn test_vec_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_vec(&TypeKind::Primitive(PrimitiveType::String)),
            "[String!]"
        );
    }

    #[test]
    fn test_hashmap_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_hashmap(
                &TypeKind::Primitive(PrimitiveType::String),
                &TypeKind::Primitive(PrimitiveType::U32)
            ),
            "JSON"
        );
    }

    #[test]
    fn test_tuple_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_tuple(&[
                TypeKind::Primitive(PrimitiveType::String),
                TypeKind::Primitive(PrimitiveType::U32)
            ]),
            "JSON"
        );
    }

    #[test]
    fn test_file_naming() {
        let m = mapper();
        assert_eq!(m.file_naming("UserProfile"), "user_profile");
        assert_eq!(m.file_naming("User"), "user");
    }

    #[test]
    fn test_output_filename() {
        let m = mapper();
        assert_eq!(m.output_filename("UserProfile"), "user_profile.graphql");
    }

    #[test]
    fn test_file_naming_kebab() {
        let m = GraphQLMapper::new().with_file_style(FileStyle::KebabCase);
        assert_eq!(m.file_naming("UserProfile"), "user-profile");
        assert_eq!(m.output_filename("UserProfile"), "user-profile.graphql");
    }

    #[test]
    fn test_generic_mapped_as_base_name() {
        let m = mapper();
        assert_eq!(
            m.map_generic(
                "Pagination",
                &[TypeKind::Named("User".to_string())]
            ),
            "Pagination"
        );
    }
}
