//! TypeScript type mapper implementation.

use typewriter_core::ir::*;
use typewriter_core::mapper::TypeMapper;
use typewriter_core::naming::{FileStyle, to_file_style};

use crate::emitter;

/// TypeScript language mapper.
///
/// Generates TypeScript interfaces from Rust structs and discriminated unions from enums.
pub struct TypeScriptMapper {
    /// Whether all fields should be `readonly`
    pub readonly: bool,
    /// File naming style (default: `kebab-case`)
    pub file_style: FileStyle,
}

impl TypeScriptMapper {
    pub fn new() -> Self {
        Self {
            readonly: false,
            file_style: FileStyle::KebabCase,
        }
    }

    pub fn with_readonly(mut self, readonly: bool) -> Self {
        self.readonly = readonly;
        self
    }

    pub fn with_file_style(mut self, style: FileStyle) -> Self {
        self.file_style = style;
        self
    }

    pub fn emit_zod_type_def(&self, def: &TypeDef) -> String {
        let mut output = self.file_header(def.name());
        let imports = emitter::render_zod_imports(self, def);
        if !imports.is_empty() {
            output.push_str(&imports);
            output.push('\n');
        }

        output.push_str(&emitter::render_zod_type_def(self, def));
        output
    }

    pub fn zod_output_filename(&self, type_name: &str) -> String {
        format!("{}.schema.ts", self.file_naming(type_name))
    }
}

impl Default for TypeScriptMapper {
    fn default() -> Self {
        Self::new()
    }
}

impl TypeMapper for TypeScriptMapper {
    fn map_primitive(&self, ty: &PrimitiveType) -> String {
        match ty {
            PrimitiveType::String => "string".to_string(),
            PrimitiveType::Bool => "boolean".to_string(),
            PrimitiveType::U8 | PrimitiveType::U16 | PrimitiveType::U32 => "number".to_string(),
            PrimitiveType::I8 | PrimitiveType::I16 | PrimitiveType::I32 => "number".to_string(),
            PrimitiveType::F32 | PrimitiveType::F64 => "number".to_string(),
            PrimitiveType::U64 | PrimitiveType::U128 => "bigint".to_string(),
            PrimitiveType::I64 | PrimitiveType::I128 => "bigint".to_string(),
            PrimitiveType::Uuid => "string".to_string(),
            PrimitiveType::DateTime | PrimitiveType::NaiveDate => "string".to_string(),
            PrimitiveType::JsonValue => "unknown".to_string(),
        }
    }

    fn map_option(&self, inner: &TypeKind) -> String {
        format!("{} | undefined", self.map_type(inner))
    }

    fn map_vec(&self, inner: &TypeKind) -> String {
        let inner_type = self.map_type(inner);
        // Wrap union types in parens for array: (A | B)[]
        if inner_type.contains('|') {
            format!("({}){}", inner_type, "[]")
        } else {
            format!("{}{}", inner_type, "[]")
        }
    }

    fn map_hashmap(&self, key: &TypeKind, value: &TypeKind) -> String {
        format!("Record<{}, {}>", self.map_type(key), self.map_type(value))
    }

    fn map_tuple(&self, elements: &[TypeKind]) -> String {
        let inner: Vec<String> = elements.iter().map(|e| self.map_type(e)).collect();
        format!("[{}]", inner.join(", "))
    }

    fn map_named(&self, name: &str) -> String {
        name.to_string()
    }

    fn emit_struct(&self, def: &StructDef) -> String {
        emitter::render_interface(self, def)
    }

    fn emit_enum(&self, def: &EnumDef) -> String {
        emitter::render_enum(self, def)
    }

    fn file_header(&self, type_name: &str) -> String {
        format!(
            "// Auto-generated by typewriter v0.4.1. DO NOT EDIT.\n\
            // Source: {}\n\
            // Regenerate: cargo typewriter generate\n\n",
            type_name
        )
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn emit_imports(&self, def: &TypeDef) -> String {
        let refs = def.collect_referenced_types();
        if refs.is_empty() {
            return String::new();
        }
        let mut output = String::new();
        for name in &refs {
            let file_name = self.file_naming(name);
            output.push_str(&format!(
                "import type {{ {} }} from './{}';\n",
                name, file_name
            ));
        }
        output
    }

    fn file_naming(&self, type_name: &str) -> String {
        to_file_style(type_name, self.file_style)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mapper() -> TypeScriptMapper {
        TypeScriptMapper::new()
    }

    #[test]
    fn test_primitive_mappings() {
        let m = mapper();
        assert_eq!(m.map_primitive(&PrimitiveType::String), "string");
        assert_eq!(m.map_primitive(&PrimitiveType::Bool), "boolean");
        assert_eq!(m.map_primitive(&PrimitiveType::U32), "number");
        assert_eq!(m.map_primitive(&PrimitiveType::I32), "number");
        assert_eq!(m.map_primitive(&PrimitiveType::F64), "number");
        assert_eq!(m.map_primitive(&PrimitiveType::U64), "bigint");
        assert_eq!(m.map_primitive(&PrimitiveType::I64), "bigint");
        assert_eq!(m.map_primitive(&PrimitiveType::Uuid), "string");
        assert_eq!(m.map_primitive(&PrimitiveType::DateTime), "string");
        assert_eq!(m.map_primitive(&PrimitiveType::JsonValue), "unknown");
    }

    #[test]
    fn test_option_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_option(&TypeKind::Primitive(PrimitiveType::U32)),
            "number | undefined"
        );
    }

    #[test]
    fn test_vec_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_vec(&TypeKind::Primitive(PrimitiveType::String)),
            "string[]"
        );
    }

    #[test]
    fn test_hashmap_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_hashmap(
                &TypeKind::Primitive(PrimitiveType::String),
                &TypeKind::Primitive(PrimitiveType::U32)
            ),
            "Record<string, number>"
        );
    }

    #[test]
    fn test_tuple_mapping() {
        let m = mapper();
        assert_eq!(
            m.map_tuple(&[
                TypeKind::Primitive(PrimitiveType::String),
                TypeKind::Primitive(PrimitiveType::U32)
            ]),
            "[string, number]"
        );
    }

    #[test]
    fn test_file_naming_kebab() {
        let m = mapper();
        assert_eq!(m.file_naming("UserProfile"), "user-profile");
        assert_eq!(m.file_naming("User"), "user");
        assert_eq!(m.file_naming("HTTPResponse"), "http-response");
    }

    #[test]
    fn test_file_naming_snake() {
        let m = TypeScriptMapper::new().with_file_style(FileStyle::SnakeCase);
        assert_eq!(m.file_naming("UserProfile"), "user_profile");
        assert_eq!(m.file_naming("HTTPResponse"), "http_response");
    }

    #[test]
    fn test_file_naming_pascal() {
        let m = TypeScriptMapper::new().with_file_style(FileStyle::PascalCase);
        assert_eq!(m.file_naming("UserProfile"), "UserProfile");
        assert_eq!(m.file_naming("HTTPResponse"), "HTTPResponse");
    }

    #[test]
    fn test_output_filename() {
        let m = mapper();
        assert_eq!(m.output_filename("UserProfile"), "user-profile.ts");
    }

    #[test]
    fn test_output_filename_pascal() {
        let m = TypeScriptMapper::new().with_file_style(FileStyle::PascalCase);
        assert_eq!(m.output_filename("UserProfile"), "UserProfile.ts");
    }

    #[test]
    fn test_zod_output_filename() {
        let m = mapper();
        assert_eq!(
            m.zod_output_filename("UserProfile"),
            "user-profile.schema.ts"
        );
    }

    #[test]
    fn test_zod_output_filename_pascal() {
        let m = TypeScriptMapper::new().with_file_style(FileStyle::PascalCase);
        assert_eq!(
            m.zod_output_filename("UserProfile"),
            "UserProfile.schema.ts"
        );
    }

    #[test]
    fn test_emit_zod_type_def() {
        let m = mapper();
        let def = TypeDef::Struct(StructDef {
            name: "User".to_string(),
            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    ty: TypeKind::Primitive(PrimitiveType::Uuid),
                    optional: false,
                    rename: None,
                    doc: None,
                    skip: false,
                    flatten: false,
                    type_override: None,
                },
                FieldDef {
                    name: "role".to_string(),
                    ty: TypeKind::Named("UserRole".to_string()),
                    optional: false,
                    rename: None,
                    doc: None,
                    skip: false,
                    flatten: false,
                    type_override: None,
                },
            ],
            doc: None,
            generics: vec![],
        });

        let output = m.emit_zod_type_def(&def);
        assert!(output.contains("import { z } from 'zod';"));
        assert!(output.contains("import { UserRoleSchema } from './user-role.schema';"));
        assert!(output.contains(
            "export const UserSchema = z.object({\"id\": z.string(), \"role\": z.lazy(() => UserRoleSchema)});"
        ));
    }

    #[test]
    fn test_emit_zod_type_def_generic_struct() {
        let m = mapper();
        let def = TypeDef::Struct(StructDef {
            name: "Pagination".to_string(),
            fields: vec![FieldDef {
                name: "items".to_string(),
                ty: TypeKind::Vec(Box::new(TypeKind::Named("T".to_string()))),
                optional: false,
                rename: None,
                doc: None,
                skip: false,
                flatten: false,
                type_override: None,
            }],
            doc: None,
            generics: vec!["T".to_string()],
        });

        let output = m.emit_zod_type_def(&def);
        assert!(output.contains(
            "export const PaginationSchema = <TSchema extends z.ZodTypeAny>(tSchema: TSchema) =>"
        ));
        assert!(output.contains("\"items\": z.array(tSchema)"));
    }

    #[test]
    fn test_emit_simple_struct() {
        let m = mapper();
        let def = StructDef {
            name: "User".to_string(),
            fields: vec![
                FieldDef {
                    name: "id".to_string(),
                    ty: TypeKind::Primitive(PrimitiveType::Uuid),
                    optional: false,
                    rename: None,
                    doc: None,
                    skip: false,
                    flatten: false,
                    type_override: None,
                },
                FieldDef {
                    name: "email".to_string(),
                    ty: TypeKind::Primitive(PrimitiveType::String),
                    optional: false,
                    rename: None,
                    doc: None,
                    skip: false,
                    flatten: false,
                    type_override: None,
                },
                FieldDef {
                    name: "age".to_string(),
                    ty: TypeKind::Option(Box::new(TypeKind::Primitive(PrimitiveType::U32))),
                    optional: true,
                    rename: None,
                    doc: None,
                    skip: false,
                    flatten: false,
                    type_override: None,
                },
            ],
            doc: None,
            generics: vec![],
        };

        let output = m.emit_struct(&def);
        assert!(output.contains("export interface User {"));
        assert!(output.contains("id: string;"));
        assert!(output.contains("email: string;"));
        assert!(output.contains("age?: number | undefined;"));
    }

    #[test]
    fn test_skipped_field() {
        let m = mapper();
        let def = StructDef {
            name: "User".to_string(),
            fields: vec![
                FieldDef {
                    name: "email".to_string(),
                    ty: TypeKind::Primitive(PrimitiveType::String),
                    optional: false,
                    rename: None,
                    doc: None,
                    skip: false,
                    flatten: false,
                    type_override: None,
                },
                FieldDef {
                    name: "password_hash".to_string(),
                    ty: TypeKind::Primitive(PrimitiveType::String),
                    optional: false,
                    rename: None,
                    doc: None,
                    skip: true,
                    flatten: false,
                    type_override: None,
                },
            ],
            doc: None,
            generics: vec![],
        };

        let output = m.emit_struct(&def);
        assert!(output.contains("email: string;"));
        assert!(!output.contains("password_hash"));
    }

    #[test]
    fn test_renamed_field() {
        let m = mapper();
        let def = StructDef {
            name: "User".to_string(),
            fields: vec![FieldDef {
                name: "user_name".to_string(),
                ty: TypeKind::Primitive(PrimitiveType::String),
                optional: false,
                rename: Some("userName".to_string()),
                doc: None,
                skip: false,
                flatten: false,
                type_override: None,
            }],
            doc: None,
            generics: vec![],
        };

        let output = m.emit_struct(&def);
        assert!(output.contains("userName: string;"));
    }

    #[test]
    fn test_simple_enum() {
        let m = mapper();
        let def = EnumDef {
            name: "Role".to_string(),
            variants: vec![
                VariantDef {
                    name: "Admin".to_string(),
                    rename: None,
                    kind: VariantKind::Unit,
                    doc: None,
                },
                VariantDef {
                    name: "User".to_string(),
                    rename: None,
                    kind: VariantKind::Unit,
                    doc: None,
                },
                VariantDef {
                    name: "Guest".to_string(),
                    rename: None,
                    kind: VariantKind::Unit,
                    doc: None,
                },
            ],
            representation: EnumRepr::External,
            doc: None,
        };

        let output = m.emit_enum(&def);
        assert!(output.contains("export type Role ="));
        assert!(output.contains("\"Admin\""));
        assert!(output.contains("\"User\""));
        assert!(output.contains("\"Guest\""));
    }
}
