//! Swift type mapper implementation.

use typewriter_core::ir::*;
use typewriter_core::mapper::TypeMapper;
use typewriter_core::naming::{to_file_style, FileStyle};

use crate::emitter;

/// Swift language mapper.
///
/// Generates Swift `Codable` structs and enums from Rust types.
pub struct SwiftMapper {
    /// File naming style (default: `PascalCase`)
    pub file_style: FileStyle,
}

impl SwiftMapper {
    pub fn new() -> Self {
        Self {
            file_style: FileStyle::PascalCase,
        }
    }

    pub fn with_file_style(mut self, style: FileStyle) -> Self {
        self.file_style = style;
        self
    }
}

impl Default for SwiftMapper {
    fn default() -> Self {
        Self::new()
    }
}

impl TypeMapper for SwiftMapper {
    fn map_primitive(&self, ty: &PrimitiveType) -> String {
        match ty {
            PrimitiveType::String => "String".to_string(),
            PrimitiveType::Bool => "Bool".to_string(),
            PrimitiveType::U8 => "UInt8".to_string(),
            PrimitiveType::U16 => "UInt16".to_string(),
            PrimitiveType::U32 => "UInt32".to_string(),
            PrimitiveType::U64 => "UInt64".to_string(),
            // Swift has no UInt128; use String for JSON safety
            PrimitiveType::U128 => "String".to_string(),
            PrimitiveType::I8 => "Int8".to_string(),
            PrimitiveType::I16 => "Int16".to_string(),
            PrimitiveType::I32 => "Int32".to_string(),
            PrimitiveType::I64 => "Int64".to_string(),
            // Same as U128
            PrimitiveType::I128 => "String".to_string(),
            PrimitiveType::F32 => "Float".to_string(),
            PrimitiveType::F64 => "Double".to_string(),
            PrimitiveType::Uuid => "UUID".to_string(),
            PrimitiveType::DateTime => "Date".to_string(),
            PrimitiveType::NaiveDate => "Date".to_string(),
            PrimitiveType::JsonValue => "AnyCodable".to_string(),
        }
    }

    fn map_option(&self, inner: &TypeKind) -> String {
        format!("{}?", self.map_type(inner))
    }

    fn map_vec(&self, inner: &TypeKind) -> String {
        format!("[{}]", self.map_type(inner))
    }

    fn map_hashmap(&self, key: &TypeKind, value: &TypeKind) -> String {
        format!("[{}: {}]", self.map_type(key), self.map_type(value))
    }

    fn map_tuple(&self, elements: &[TypeKind]) -> String {
        let type_strs: Vec<String> = elements.iter().map(|e| self.map_type(e)).collect();
        format!("({})", type_strs.join(", "))
    }

    fn map_named(&self, name: &str) -> String {
        name.to_string()
    }

    fn emit_struct(&self, def: &StructDef) -> String {
        emitter::render_struct(self, def)
    }

    fn emit_enum(&self, def: &EnumDef) -> String {
        emitter::render_enum(self, def)
    }

    fn file_header(&self, type_name: &str) -> String {
        format!(
            "// Code generated by typewriter v0.3.1. DO NOT EDIT.\n\
             // Source: {}\n\n\
             import Foundation\n\n",
            type_name
        )
    }

    fn file_extension(&self) -> &str {
        "swift"
    }

    fn emit_imports(&self, _def: &TypeDef) -> String {
        // Swift uses the Foundation import in file_header for most types.
        // No additional per-type imports needed for now.
        String::new()
    }

    fn file_naming(&self, type_name: &str) -> String {
        to_file_style(type_name, self.file_style)
    }

    fn map_generic(&self, name: &str, params: &[TypeKind]) -> String {
        let param_strs: Vec<String> = params.iter().map(|p| self.map_type(p)).collect();
        format!("{}<{}>", name, param_strs.join(", "))
    }
}
