//! Go type mapper implementation.

use typewriter_core::ir::*;
use typewriter_core::mapper::TypeMapper;
use typewriter_core::naming::{FileStyle, to_file_style};

use crate::emitter;

/// Go language mapper.
///
/// Generates Go structs from Rust structs and Go types from Rust enums.
pub struct GoMapper {
    /// File naming style (default: `snake_case`)
    pub file_style: FileStyle,
    /// Package name (default: "types")
    pub package_name: String,
}

impl GoMapper {
    pub fn new() -> Self {
        Self {
            file_style: FileStyle::SnakeCase,
            package_name: "types".to_string(),
        }
    }

    pub fn with_file_style(mut self, style: FileStyle) -> Self {
        self.file_style = style;
        self
    }

    pub fn with_package_name(mut self, name: &str) -> Self {
        self.package_name = name.to_string();
        self
    }
}

impl Default for GoMapper {
    fn default() -> Self {
        Self::new()
    }
}

impl TypeMapper for GoMapper {
    fn map_primitive(&self, ty: &PrimitiveType) -> String {
        match ty {
            PrimitiveType::String => "string".to_string(),
            PrimitiveType::Bool => "bool".to_string(),
            PrimitiveType::U8 => "uint8".to_string(),
            PrimitiveType::U16 => "uint16".to_string(),
            PrimitiveType::U32 => "uint32".to_string(),
            PrimitiveType::U64 => "uint64".to_string(),
            // Go has no uint128; use string or big.Int, assuming string is safer for JSON
            PrimitiveType::U128 => "string".to_string(),
            PrimitiveType::I8 => "int8".to_string(),
            PrimitiveType::I16 => "int16".to_string(),
            PrimitiveType::I32 => "int32".to_string(),
            PrimitiveType::I64 => "int64".to_string(),
            // Same as u128
            PrimitiveType::I128 => "string".to_string(),
            PrimitiveType::F32 => "float32".to_string(),
            PrimitiveType::F64 => "float64".to_string(),
            PrimitiveType::Uuid => "string".to_string(),
            PrimitiveType::DateTime => "time.Time".to_string(),
            PrimitiveType::NaiveDate => "time.Time".to_string(),
            PrimitiveType::JsonValue => "interface{}".to_string(),
        }
    }

    fn map_option(&self, inner: &TypeKind) -> String {
        // In Go, options are often represented as pointers for json omitempty
        format!("*{}", self.map_type(inner))
    }

    fn map_vec(&self, inner: &TypeKind) -> String {
        format!("[]{}", self.map_type(inner))
    }

    fn map_hashmap(&self, key: &TypeKind, value: &TypeKind) -> String {
        format!("map[{}]{}", self.map_type(key), self.map_type(value))
    }

    fn map_tuple(&self, elements: &[TypeKind]) -> String {
        // Go doesn't have tuples. We can generate an anonymous struct.
        let mut fields = Vec::new();
        for (i, e) in elements.iter().enumerate() {
            fields.push(format!("Field{} {}", i, self.map_type(e)));
        }
        format!("struct {{\n\t\t{}\n\t}}", fields.join("\n\t\t"))
    }

    fn map_named(&self, name: &str) -> String {
        name.to_string()
    }

    fn emit_struct(&self, def: &StructDef) -> String {
        emitter::render_struct(self, def)
    }

    fn emit_enum(&self, def: &EnumDef) -> String {
        emitter::render_enum(self, def)
    }

    fn file_header(&self, type_name: &str) -> String {
        format!(
            "// Code generated by typewriter v0.4.1. DO NOT EDIT.\n\
             // Source: {}\n\n\
             package {}\n\n",
            type_name, self.package_name
        )
    }

    fn file_extension(&self) -> &str {
        "go"
    }

    fn emit_imports(&self, def: &TypeDef) -> String {
        let mut std_imports = std::collections::BTreeSet::new();

        fn collect_std_imports(ty: &TypeKind, imports: &mut std::collections::BTreeSet<String>) {
            match ty {
                TypeKind::Primitive(PrimitiveType::DateTime | PrimitiveType::NaiveDate) => {
                    imports.insert("time".to_string());
                }
                TypeKind::Option(inner) => collect_std_imports(inner, imports),
                TypeKind::Vec(inner) => collect_std_imports(inner, imports),
                TypeKind::HashMap(k, v) => {
                    collect_std_imports(k, imports);
                    collect_std_imports(v, imports);
                }
                TypeKind::Tuple(elements) => {
                    for e in elements {
                        collect_std_imports(e, imports);
                    }
                }
                TypeKind::Generic(_, params) => {
                    for p in params {
                        collect_std_imports(p, imports);
                    }
                }
                _ => {}
            }
        }

        match def {
            TypeDef::Struct(s) => {
                for field in &s.fields {
                    if !field.skip {
                        collect_std_imports(&field.ty, &mut std_imports);
                    }
                }
            }
            TypeDef::Enum(e) => {
                // If it's a data carrying enum, we need json to implement UnmarshalJSON
                let _all_unit = e
                    .variants
                    .iter()
                    .all(|v| matches!(v.kind, VariantKind::Unit));
                for variant in &e.variants {
                    if let VariantKind::Struct(fields) = &variant.kind {
                        for field in fields {
                            if !field.skip {
                                collect_std_imports(&field.ty, &mut std_imports);
                            }
                        }
                    } else if let VariantKind::Tuple(types) = &variant.kind {
                        for ty in types {
                            collect_std_imports(ty, &mut std_imports);
                        }
                    }
                }
            }
        }

        if std_imports.is_empty() {
            return String::new();
        }

        let mut output = String::from("import (\n");
        for import in std_imports {
            output.push_str(&format!("\t\"{}\"\n", import));
        }
        output.push_str(")\n\n");
        output
    }

    fn file_naming(&self, type_name: &str) -> String {
        to_file_style(type_name, self.file_style)
    }

    fn map_generic(&self, name: &str, params: &[TypeKind]) -> String {
        let param_strs: Vec<String> = params.iter().map(|p| self.map_type(p)).collect();
        // Go 1.18+ generics syntax
        format!("{}[{}]", name, param_strs.join(", "))
    }
}
