//! Standalone CLI for typewriter type synchronization.
//!
//! The primary binary is `typebridge`. A `typewriter` binary remains available
//! as a compatibility alias, and `cargo-typewriter` remains available for
//! `cargo typewriter` workflows.

use anyhow::{Context, Result, anyhow};
use clap::{Parser, Subcommand, ValueEnum};
use colored::Colorize;
use notify::{Event, RecommendedWatcher, RecursiveMode, Watcher};
use serde_json::{Value, json};
use similar::TextDiff;
use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsString;
use std::path::{Path, PathBuf};
use std::sync::mpsc;
use std::time::{Duration, Instant};
use typewriter_core::config::TypewriterConfig;
use typewriter_engine::drift::{self, DriftStatus};
use typewriter_engine::emit;
use typewriter_engine::plugin_registry;
use typewriter_engine::{
    Language, LanguageTarget, TypeSpec, all_languages, parse_languages, project, scan,
};

const DEFAULT_CONFIG: &str = r#"# typewriter.toml
# Generated by `typebridge init`.

[typescript]
output_dir = "./generated/typescript"
zod = true
readonly = false

[python]
output_dir = "./generated/python"
pydantic_v2 = true

[go]
output_dir = "./generated/go"
package_name = "types"

[swift]
output_dir = "./generated/swift"

[kotlin]
output_dir = "./generated/kotlin"
package_name = "types"

[graphql]
output_dir = "./generated/graphql"

[json_schema]
output_dir = "./generated/json-schema"

# Plugins are experimental in v1.0.0. They are intended for local testing,
# not as a stable community plugin ABI.
[plugins]
# dir = "~/.typewriter/plugins"
# paths = []
"#;

#[derive(Parser, Debug)]
#[command(
    name = "typebridge",
    version,
    about = "Generate and verify cross-language types from Rust source",
    after_help = "Examples:\n  typebridge generate --all\n  typebridge generate src/models.rs --lang typescript,python\n  typebridge check --ci\n  typebridge watch\n  typebridge init\n  typebridge doctor"
)]
struct Cli {
    /// Path to a typewriter.toml config file.
    #[arg(long, global = true, value_name = "PATH")]
    config: Option<PathBuf>,
    /// Output format for commands that support structured output.
    #[arg(long, global = true, value_enum, default_value_t = OutputFormat::Text)]
    format: OutputFormat,
    /// Print additional diagnostic details.
    #[arg(long, global = true)]
    verbose: bool,
    /// Report planned changes without writing generated files.
    #[arg(long, global = true)]
    dry_run: bool,
    #[command(subcommand)]
    command: Commands,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
enum OutputFormat {
    Text,
    Json,
}

impl OutputFormat {
    fn as_str(self) -> &'static str {
        match self {
            Self::Text => "text",
            Self::Json => "json",
        }
    }
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Generate type files from Rust source definitions.
    Generate {
        /// Generate from a single Rust source file.
        file: Option<PathBuf>,
        /// Generate from all Rust files in the project.
        #[arg(long)]
        all: bool,
        /// Restrict generation to languages (comma-separated).
        #[arg(long, value_delimiter = ',')]
        lang: Vec<String>,
        /// Show unified diffs for changed files.
        #[arg(long)]
        diff: bool,
    },
    /// Check if generated files are in sync with Rust source.
    Check {
        /// Exit with code 1 if drift is detected.
        #[arg(long)]
        ci: bool,
        /// Print structured JSON drift report to stdout.
        #[arg(long)]
        json: bool,
        /// Write structured JSON drift report to a file.
        #[arg(long)]
        json_out: Option<PathBuf>,
        /// Restrict check to languages (comma-separated).
        #[arg(long, value_delimiter = ',')]
        lang: Vec<String>,
    },
    /// Watch Rust files and regenerate on save.
    Watch {
        /// Directory to watch recursively (default: ./src).
        path: Option<PathBuf>,
        /// Restrict generation to languages (comma-separated).
        #[arg(long, value_delimiter = ',')]
        lang: Vec<String>,
        /// Debounce interval for filesystem events.
        #[arg(long, default_value_t = 50)]
        debounce_ms: u64,
    },
    /// Create a starter typewriter.toml config file.
    Init {
        /// Overwrite an existing config file.
        #[arg(long)]
        force: bool,
    },
    /// Print environment and project diagnostics.
    Doctor,
    /// Manage experimental typewriter plugins.
    Plugin {
        #[command(subcommand)]
        action: PluginAction,
    },
}

#[derive(Subcommand, Debug)]
enum PluginAction {
    /// List all loaded plugins.
    List,
    /// Validate a plugin shared library.
    Validate {
        /// Path to the plugin shared library.
        path: PathBuf,
    },
    /// Show info about a specific loaded plugin.
    Info {
        /// Plugin language ID (e.g. "ruby", "php", "dart").
        name: String,
    },
}

#[derive(Debug)]
struct CliContext {
    cwd: PathBuf,
    project_root: Option<PathBuf>,
    config_path: PathBuf,
    config_exists: bool,
    config: TypewriterConfig,
    config_error: Option<String>,
    format: OutputFormat,
    verbose: bool,
    dry_run: bool,
}

#[derive(Debug)]
struct GenerationEvent {
    action: &'static str,
    path: String,
    language: String,
    type_name: String,
}

#[derive(Default, Debug)]
struct GenerationSummary {
    created: usize,
    updated: usize,
    unchanged: usize,
}

pub fn run() -> Result<i32> {
    run_with_args(std::env::args_os())
}

pub fn run_with_args<I, T>(args: I) -> Result<i32>
where
    I: IntoIterator<Item = T>,
    T: Into<OsString> + Clone,
{
    let cli = match Cli::try_parse_from(args) {
        Ok(cli) => cli,
        Err(err) => {
            let code = if err.use_stderr() { 2 } else { 0 };
            err.print()
                .map_err(|print_err| anyhow!("failed to print clap error: {print_err}"))?;
            return Ok(code);
        }
    };

    let ctx = build_context(&cli)?;

    match cli.command {
        Commands::Generate {
            file,
            all,
            lang,
            diff,
        } => cmd_generate(&ctx, file, all, lang, diff),
        Commands::Check {
            ci,
            json,
            json_out,
            lang,
        } => cmd_check(&ctx, ci, json, json_out, lang),
        Commands::Watch {
            path,
            lang,
            debounce_ms,
        } => cmd_watch(&ctx, path, lang, debounce_ms),
        Commands::Init { force } => cmd_init(&ctx, force),
        Commands::Doctor => cmd_doctor(&ctx),
        Commands::Plugin { action } => cmd_plugin(&ctx, action),
    }
}

fn build_context(cli: &Cli) -> Result<CliContext> {
    let cwd = std::env::current_dir().context("failed to resolve current directory")?;
    let project_root = project::discover_project_root(&cwd).ok();
    let base_dir = project_root.clone().unwrap_or_else(|| cwd.clone());
    let config_path = cli
        .config
        .clone()
        .map(|path| resolve_input_path(path, &cwd))
        .unwrap_or_else(|| base_dir.join("typewriter.toml"));
    let config_exists = config_path.exists();

    let (config, config_error) = if config_exists {
        match load_config_file(&config_path) {
            Ok(config) => (config, None),
            Err(err) => (TypewriterConfig::default(), Some(err.to_string())),
        }
    } else {
        (TypewriterConfig::default(), None)
    };

    Ok(CliContext {
        cwd,
        project_root,
        config_path,
        config_exists,
        config,
        config_error,
        format: cli.format,
        verbose: cli.verbose,
        dry_run: cli.dry_run,
    })
}

fn load_config_file(path: &Path) -> Result<TypewriterConfig> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read config {}", path.display()))?;
    toml::from_str(&content).with_context(|| format!("failed to parse config {}", path.display()))
}

fn require_project_root(ctx: &CliContext) -> Result<&Path> {
    ctx.project_root.as_deref().ok_or_else(|| {
        anyhow!(
            "could not find a Cargo.toml in this directory or any parent. Run typebridge from a Rust project root or pass --config from inside a Rust project."
        )
    })
}

fn ensure_config_valid(ctx: &CliContext) -> Result<()> {
    if let Some(err) = &ctx.config_error {
        anyhow::bail!("{err}");
    }
    Ok(())
}

/// Extract only the built-in Language values from a list of LanguageTargets.
fn extract_builtin_filter(targets: &[LanguageTarget]) -> Vec<Language> {
    targets
        .iter()
        .filter_map(|target| match target {
            LanguageTarget::BuiltIn(lang) => Some(*lang),
            LanguageTarget::Plugin(_) => None,
        })
        .collect()
}

fn apply_target_filter(mut specs: Vec<TypeSpec>, targets: &[LanguageTarget]) -> Vec<TypeSpec> {
    if targets.is_empty() {
        return specs;
    }

    specs
        .drain(..)
        .filter_map(|mut spec| {
            spec.targets.retain(|target| targets.contains(target));
            if spec.targets.is_empty() {
                None
            } else {
                Some(spec)
            }
        })
        .collect()
}

fn cmd_generate(
    ctx: &CliContext,
    file: Option<PathBuf>,
    all: bool,
    lang: Vec<String>,
    diff: bool,
) -> Result<i32> {
    ensure_config_valid(ctx)?;

    if all == file.is_some() {
        anyhow::bail!("use exactly one input mode: either `generate <file>` or `generate --all`");
    }

    let project_root = require_project_root(ctx)?;
    let lang_targets = parse_languages(&lang)?;
    let registry = plugin_registry::build_registry_from_config(&ctx.config).unwrap_or_default();

    let specs = if all {
        scan::scan_project(project_root)?
    } else {
        let source = resolve_input_path(file.expect("validated"), &ctx.cwd);
        scan::scan_file(&source)?
    };
    let specs = apply_target_filter(specs, &lang_targets);

    if ctx.verbose && ctx.format == OutputFormat::Text {
        eprintln!("{} {}", "Project root:".bold(), project_root.display());
        eprintln!("{} {}", "Config:".bold(), ctx.config_path.display());
    }

    let rendered = emit::render_specs_deduped_with_plugins(
        &specs,
        project_root,
        &ctx.config,
        &[],
        false,
        Some(&registry),
    )?;

    let started = Instant::now();
    let mut summary = GenerationSummary::default();
    let mut events = Vec::new();
    let mut before_contents = BTreeMap::new();

    for file in &rendered {
        if let Ok(existing) = std::fs::read_to_string(&file.output_path) {
            before_contents.insert(file.output_path.clone(), existing);
        }
    }

    if !ctx.dry_run {
        emit::write_generated_files(&rendered)?;
    }

    for file in &rendered {
        let rel = rel_path(project_root, &file.output_path);
        let (action, label) = match before_contents.get(&file.output_path) {
            None => {
                summary.created += 1;
                if ctx.dry_run {
                    ("create", "Would create".green())
                } else {
                    ("create", "Created".green())
                }
            }
            Some(existing) if existing == &file.content => {
                summary.unchanged += 1;
                ("unchanged", "Unchanged".bright_black())
            }
            Some(existing) => {
                summary.updated += 1;
                if diff {
                    print_diff(project_root, &file.output_path, existing, &file.content);
                }
                if ctx.dry_run {
                    ("update", "Would update".yellow())
                } else {
                    ("update", "Updated".yellow())
                }
            }
        };

        if !before_contents.contains_key(&file.output_path) && diff {
            print_diff(project_root, &file.output_path, "", &file.content);
        }

        if ctx.format == OutputFormat::Text {
            eprintln!("{} {} [{}]", label, rel, file.language_label);
        }

        events.push(GenerationEvent {
            action,
            path: rel,
            language: file.language_label.clone(),
            type_name: file.type_name.clone(),
        });
    }

    if ctx.format == OutputFormat::Json {
        write_json_stdout(json!({
            "command": "generate",
            "dry_run": ctx.dry_run,
            "project_root": project_root,
            "config": ctx.config_path,
            "elapsed_ms": started.elapsed().as_millis(),
            "summary": {
                "created": summary.created,
                "updated": summary.updated,
                "unchanged": summary.unchanged,
                "rendered": rendered.len(),
            },
            "files": events.iter().map(|event| json!({
                "action": event.action,
                "path": event.path,
                "language": event.language,
                "type_name": event.type_name,
            })).collect::<Vec<_>>(),
        }))?;
    } else {
        let verb = if ctx.dry_run {
            "Dry run complete"
        } else {
            "Generation complete"
        };
        eprintln!(
            "{} in {}ms (created: {}, updated: {}, unchanged: {})",
            verb.bold(),
            started.elapsed().as_millis(),
            summary.created,
            summary.updated,
            summary.unchanged
        );
    }

    Ok(0)
}

fn cmd_check(
    ctx: &CliContext,
    ci: bool,
    json_stdout: bool,
    json_out: Option<PathBuf>,
    lang: Vec<String>,
) -> Result<i32> {
    ensure_config_valid(ctx)?;

    let project_root = require_project_root(ctx)?;
    let lang_targets = parse_languages(&lang)?;
    let lang_filter = extract_builtin_filter(&lang_targets);
    let registry = plugin_registry::build_registry_from_config(&ctx.config).unwrap_or_default();

    let specs = apply_target_filter(scan::scan_project(project_root)?, &lang_targets);
    let rendered = emit::render_specs_deduped_with_plugins(
        &specs,
        project_root,
        &ctx.config,
        &[],
        false,
        Some(&registry),
    )?;

    let report = drift::build_drift_report(&rendered, project_root, &ctx.config, &lang_filter)?;
    let should_print_json = json_stdout || ctx.format == OutputFormat::Json;

    if should_print_json {
        println!("{}", serde_json::to_string_pretty(&report)?);
    } else {
        if ctx.verbose {
            eprintln!("{} {}", "Project root:".bold(), project_root.display());
            eprintln!("{} {}", "Config:".bold(), ctx.config_path.display());
        }
        print_human_report(&report);
    }

    if let Some(path) = json_out {
        let full = resolve_input_path(path, &ctx.cwd);
        if ctx.dry_run {
            if ctx.format == OutputFormat::Text {
                eprintln!("{} {}", "Would write JSON report:".yellow(), full.display());
            }
        } else {
            if let Some(parent) = full.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&full, serde_json::to_string_pretty(&report)?)
                .with_context(|| format!("failed to write JSON report to {}", full.display()))?;
            if ctx.format == OutputFormat::Text {
                eprintln!("{} {}", "Wrote JSON report:".green(), full.display());
            }
        }
    }

    if ci && drift::has_drift(&report.summary) {
        if ctx.format == OutputFormat::Text {
            eprintln!("{} drift detected in CI mode", "Error:".red().bold());
        }
        return Ok(1);
    }

    Ok(0)
}

fn cmd_watch(
    ctx: &CliContext,
    path: Option<PathBuf>,
    lang: Vec<String>,
    debounce_ms: u64,
) -> Result<i32> {
    ensure_config_valid(ctx)?;

    if ctx.dry_run {
        anyhow::bail!("watch does not support --dry-run because it is a long-running writer");
    }
    if ctx.format == OutputFormat::Json {
        anyhow::bail!("watch does not support --format json");
    }

    let project_root = require_project_root(ctx)?;
    let watch_root = resolve_input_path(path.unwrap_or_else(|| PathBuf::from("src")), &ctx.cwd);
    let lang_targets = parse_languages(&lang)?;
    let registry = plugin_registry::build_registry_from_config(&ctx.config).unwrap_or_default();

    let (tx, rx) = mpsc::channel();
    let mut watcher = RecommendedWatcher::new(
        move |result| {
            let _ = tx.send(result);
        },
        notify::Config::default(),
    )?;

    watcher.watch(&watch_root, RecursiveMode::Recursive)?;

    if ctx.verbose {
        eprintln!("{} {}", "Project root:".bold(), project_root.display());
        eprintln!("{} {}", "Config:".bold(), ctx.config_path.display());
    }
    eprintln!(
        "{} {} (debounce={}ms)",
        "Watching".green().bold(),
        watch_root.display(),
        debounce_ms
    );

    loop {
        let first = match rx.recv() {
            Ok(event) => event,
            Err(err) => {
                eprintln!("{} watcher channel closed: {}", "Error:".red(), err);
                return Ok(1);
            }
        };

        let mut changed_files = BTreeSet::new();
        collect_changed_rust_files(first, &mut changed_files);

        while let Ok(event) = rx.recv_timeout(Duration::from_millis(debounce_ms)) {
            collect_changed_rust_files(event, &mut changed_files);
        }

        if changed_files.is_empty() {
            continue;
        }

        let batch_started = Instant::now();
        let mut specs = Vec::new();

        for changed in &changed_files {
            eprintln!("{} {}", "Changed:".cyan(), rel_path(project_root, changed));
            if changed.exists() {
                match scan::scan_file(changed) {
                    Ok(mut found) => specs.append(&mut found),
                    Err(err) => eprintln!("{} {}", "Scan error:".red(), err),
                }
            }
        }

        let specs = apply_target_filter(specs, &lang_targets);
        if specs.is_empty() {
            continue;
        }

        let mut names: Vec<_> = specs
            .iter()
            .map(|spec| spec.type_def.name().to_string())
            .collect();
        names.sort();
        names.dedup();
        for name in names {
            eprintln!("{} {}", "Detected TypeWriter type:".blue(), name);
        }

        let rendered = emit::render_specs_deduped_with_plugins(
            &specs,
            project_root,
            &ctx.config,
            &[],
            false,
            Some(&registry),
        )?;

        let mut updated = 0usize;
        for file in rendered {
            let before = std::fs::read_to_string(&file.output_path).ok();
            emit::write_generated_files(std::slice::from_ref(&file))?;

            let changed = before
                .map(|content| content != file.content)
                .unwrap_or(true);
            if changed {
                updated += 1;
            }

            eprintln!(
                "{} {} [{}]",
                "Regenerated".green(),
                rel_path(project_root, &file.output_path),
                file.language_label
            );
        }

        eprintln!(
            "{} {} file(s) in {}ms",
            "Done".bold(),
            updated,
            batch_started.elapsed().as_millis()
        );
    }
}

fn cmd_init(ctx: &CliContext, force: bool) -> Result<i32> {
    if ctx.dry_run {
        if ctx.format == OutputFormat::Json {
            write_json_stdout(json!({
                "command": "init",
                "dry_run": true,
                "path": ctx.config_path,
                "exists": ctx.config_path.exists(),
                "would_write": !ctx.config_path.exists() || force,
                "would_overwrite": ctx.config_path.exists() && force,
                "content": DEFAULT_CONFIG,
            }))?;
        } else if ctx.config_path.exists() && !force {
            eprintln!(
                "{} {} already exists. Use --force to overwrite it.",
                "Would refuse:".yellow(),
                ctx.config_path.display()
            );
        } else {
            eprintln!(
                "{} {}",
                if ctx.config_path.exists() {
                    "Would overwrite:".yellow()
                } else {
                    "Would create:".green()
                },
                ctx.config_path.display()
            );
        }
        return Ok(0);
    }

    if ctx.config_path.exists() && !force {
        anyhow::bail!(
            "{} already exists. Use --force to overwrite it.",
            ctx.config_path.display()
        );
    }

    if let Some(parent) = ctx.config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&ctx.config_path, DEFAULT_CONFIG)
        .with_context(|| format!("failed to write {}", ctx.config_path.display()))?;

    if ctx.format == OutputFormat::Json {
        write_json_stdout(json!({
            "command": "init",
            "dry_run": false,
            "path": ctx.config_path,
            "overwritten": force,
        }))?;
    } else {
        eprintln!("{} {}", "Created".green(), ctx.config_path.display());
    }

    Ok(0)
}

fn cmd_doctor(ctx: &CliContext) -> Result<i32> {
    let registry_result = if ctx.config_error.is_none() {
        Some(plugin_registry::build_registry_from_config(&ctx.config))
    } else {
        None
    };

    let plugin_json = match &registry_result {
        Some(Ok(registry)) => {
            let plugins = registry.list();
            json!({
                "experimental": true,
                "status": "ok",
                "loaded": plugins.len(),
                "plugins": plugins.iter().map(|plugin| json!({
                    "language_id": plugin.language_id,
                    "language_name": plugin.language_name,
                    "version": plugin.version,
                    "file_extension": plugin.file_extension,
                    "output_dir": plugin.default_output_dir,
                    "source_path": plugin.source_path,
                })).collect::<Vec<_>>(),
            })
        }
        Some(Err(err)) => json!({
            "experimental": true,
            "status": "error",
            "error": err.to_string(),
        }),
        None => json!({
            "experimental": true,
            "status": "skipped",
            "error": "config is invalid",
        }),
    };

    let ok = ctx.config_error.is_none()
        && registry_result
            .as_ref()
            .map(|result| result.is_ok())
            .unwrap_or(false);

    if ctx.format == OutputFormat::Json {
        write_json_stdout(json!({
            "binary": "typebridge",
            "version": env!("CARGO_PKG_VERSION"),
            "current_dir": ctx.cwd,
            "project_root": ctx.project_root,
            "config": {
                "path": ctx.config_path,
                "exists": ctx.config_exists,
                "status": if ctx.config_error.is_some() { "invalid" } else if ctx.config_exists { "loaded" } else { "default" },
                "error": ctx.config_error,
            },
            "output_format": ctx.format.as_str(),
            "dry_run": ctx.dry_run,
            "built_in_targets": built_in_target_labels(),
            "plugins": plugin_json,
        }))?;
    } else {
        eprintln!(
            "{} typebridge {}",
            "Binary:".bold(),
            env!("CARGO_PKG_VERSION")
        );
        eprintln!("{} {}", "Current dir:".bold(), ctx.cwd.display());
        match &ctx.project_root {
            Some(root) => eprintln!("{} {}", "Project root:".bold(), root.display()),
            None => eprintln!("{} not found", "Project root:".bold()),
        }
        eprintln!("{} {}", "Config path:".bold(), ctx.config_path.display());
        match &ctx.config_error {
            Some(err) => eprintln!("{} {}", "Config:".red().bold(), err),
            None if ctx.config_exists => eprintln!("{} loaded", "Config:".green().bold()),
            None => eprintln!("{} using defaults", "Config:".yellow().bold()),
        }
        eprintln!("{} {}", "Output format:".bold(), ctx.format.as_str());
        eprintln!("{} {}", "Dry run:".bold(), ctx.dry_run);
        eprintln!(
            "{} {}",
            "Built-in targets:".bold(),
            built_in_target_labels().join(", ")
        );
        match &registry_result {
            Some(Ok(registry)) => eprintln!(
                "{} experimental, {} loaded",
                "Plugins:".bold(),
                registry.list().len()
            ),
            Some(Err(err)) => eprintln!("{} experimental, error: {}", "Plugins:".red().bold(), err),
            None => eprintln!("{} experimental, skipped", "Plugins:".yellow().bold()),
        }
    }

    Ok(if ok { 0 } else { 1 })
}

fn cmd_plugin(ctx: &CliContext, action: PluginAction) -> Result<i32> {
    ensure_config_valid(ctx)?;
    let registry = plugin_registry::build_registry_from_config(&ctx.config)?;

    match action {
        PluginAction::List => {
            let plugins = registry.list();
            if ctx.format == OutputFormat::Json {
                write_json_stdout(json!({
                    "experimental": true,
                    "plugins": plugins.iter().map(|plugin| json!({
                        "language_id": plugin.language_id,
                        "language_name": plugin.language_name,
                        "version": plugin.version,
                        "file_extension": plugin.file_extension,
                        "output_dir": plugin.default_output_dir,
                        "source_path": plugin.source_path,
                    })).collect::<Vec<_>>(),
                }))?;
            } else if plugins.is_empty() {
                eprintln!("{}", "No plugins loaded.".bright_black());
                eprintln!(
                    "  Plugins are experimental in v1.0.0. Configure local shared libraries with [plugins] in typewriter.toml."
                );
            } else {
                eprintln!(
                    "{} {} experimental plugin(s) loaded:\n",
                    "Plugins:".bold(),
                    plugins.len()
                );
                for plugin in &plugins {
                    eprintln!("  {} v{}", plugin.language_name.bold(), plugin.version);
                    eprintln!("    Language ID:  {}", plugin.language_id);
                    eprintln!("    Extension:    .{}", plugin.file_extension);
                    eprintln!("    Output dir:   {}", plugin.default_output_dir);
                    if let Some(path) = &plugin.source_path {
                        eprintln!("    Loaded from:  {}", path.display());
                    }
                    eprintln!();
                }
            }
            Ok(0)
        }
        PluginAction::Validate { path } => {
            let full = resolve_input_path(path, &ctx.cwd);
            if ctx.format == OutputFormat::Text {
                eprintln!("Validating experimental plugin: {}...", full.display());
            }
            let mut test_registry = typewriter_engine::PluginRegistry::new();
            match test_registry.load_plugin(&full) {
                Ok(()) => {
                    let plugins = test_registry.list();
                    if ctx.format == OutputFormat::Json {
                        write_json_stdout(json!({
                            "valid": true,
                            "experimental": true,
                            "path": full,
                            "plugin": plugins.first().map(|plugin| json!({
                                "language_id": plugin.language_id,
                                "language_name": plugin.language_name,
                                "version": plugin.version,
                                "file_extension": plugin.file_extension,
                            })),
                        }))?;
                    } else if let Some(plugin) = plugins.first() {
                        eprintln!("{} Plugin is valid.", "OK:".green().bold());
                        eprintln!("  Name:       {}", plugin.language_name);
                        eprintln!("  Language:   {}", plugin.language_id);
                        eprintln!("  Version:    {}", plugin.version);
                        eprintln!("  Extension:  .{}", plugin.file_extension);
                    }
                    Ok(0)
                }
                Err(err) => {
                    if ctx.format == OutputFormat::Json {
                        write_json_stdout(json!({
                            "valid": false,
                            "experimental": true,
                            "path": full,
                            "error": err.to_string(),
                        }))?;
                    } else {
                        eprintln!(
                            "{} Plugin validation failed: {}",
                            "Error:".red().bold(),
                            err
                        );
                    }
                    Ok(1)
                }
            }
        }
        PluginAction::Info { name } => {
            let plugins = registry.list();
            if let Some(plugin) = plugins.iter().find(|plugin| plugin.language_id == name) {
                if ctx.format == OutputFormat::Json {
                    write_json_stdout(json!({
                        "experimental": true,
                        "plugin": {
                            "language_id": plugin.language_id,
                            "language_name": plugin.language_name,
                            "version": plugin.version,
                            "file_extension": plugin.file_extension,
                            "output_dir": plugin.default_output_dir,
                            "source_path": plugin.source_path,
                        }
                    }))?;
                } else {
                    eprintln!("{} {}", "Plugin:".bold(), plugin.language_name);
                    eprintln!("  Language ID:  {}", plugin.language_id);
                    eprintln!("  Version:      {}", plugin.version);
                    eprintln!("  Extension:    .{}", plugin.file_extension);
                    eprintln!("  Output dir:   {}", plugin.default_output_dir);
                    if let Some(path) = &plugin.source_path {
                        eprintln!("  Loaded from:  {}", path.display());
                    }
                }
                Ok(0)
            } else {
                if ctx.format == OutputFormat::Json {
                    write_json_stdout(json!({
                        "experimental": true,
                        "error": format!("no plugin found with language ID '{name}'"),
                    }))?;
                } else {
                    eprintln!(
                        "{} No plugin found with language ID '{}'",
                        "Error:".red().bold(),
                        name
                    );
                }
                Ok(1)
            }
        }
    }
}

fn built_in_target_labels() -> Vec<&'static str> {
    all_languages()
        .into_iter()
        .map(emit::language_label)
        .collect()
}

fn write_json_stdout(value: Value) -> Result<()> {
    println!("{}", serde_json::to_string_pretty(&value)?);
    Ok(())
}

fn print_human_report(report: &drift::DriftReport) {
    for entry in &report.entries {
        let symbol = match entry.status {
            DriftStatus::UpToDate => "OK".green(),
            DriftStatus::OutOfSync => "DRIFT".yellow(),
            DriftStatus::Missing => "MISSING".red(),
            DriftStatus::Orphaned => "ORPHAN".magenta(),
        };

        eprintln!(
            "{} {} [{}] - {}",
            symbol, entry.output_path, entry.language, entry.reason
        );
    }

    eprintln!(
        "{} up_to_date={}, out_of_sync={}, missing={}, orphaned={}",
        "Summary:".bold(),
        report.summary.up_to_date,
        report.summary.out_of_sync,
        report.summary.missing,
        report.summary.orphaned
    );
}

fn print_diff(project_root: &Path, path: &Path, before: &str, after: &str) {
    let rel = rel_path(project_root, path);
    let diff = TextDiff::from_lines(before, after)
        .unified_diff()
        .context_radius(3)
        .header(&format!("a/{}", rel), &format!("b/{}", rel))
        .to_string();

    if !diff.trim().is_empty() {
        println!("{}", diff);
    }
}

fn collect_changed_rust_files(event: Result<Event, notify::Error>, files: &mut BTreeSet<PathBuf>) {
    let event = match event {
        Ok(event) => event,
        Err(err) => {
            eprintln!("{} {}", "Watch error:".red(), err);
            return;
        }
    };

    for path in event.paths {
        if path.extension().map(|ext| ext == "rs").unwrap_or(false) {
            files.insert(path);
        }
    }
}

fn rel_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
}

fn resolve_input_path(path: PathBuf, cwd: &Path) -> PathBuf {
    if path.is_absolute() {
        path
    } else {
        cwd.join(path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_invalid_generate_mode() {
        let err = run_with_args(["typebridge", "generate"]).unwrap_err();
        assert!(err.to_string().contains("use exactly one input mode"));
    }

    #[test]
    fn parses_comma_separated_langs() {
        let parsed = parse_languages(&["typescript,python".to_string()]).unwrap();
        assert_eq!(
            parsed,
            vec![
                LanguageTarget::BuiltIn(Language::TypeScript),
                LanguageTarget::BuiltIn(Language::Python),
            ]
        );
    }

    #[test]
    fn parses_plugin_languages() {
        let parsed = parse_languages(&["ruby,php".to_string()]).unwrap();
        assert_eq!(
            parsed,
            vec![
                LanguageTarget::Plugin("ruby".to_string()),
                LanguageTarget::Plugin("php".to_string()),
            ]
        );
    }
}
